service: cardsmulti2
frameworkVersion: "1.48.2"

custom:
  currentStage: ${opt:stage, self:provider.stage}
  lambdaRunTime: python3.7
  socketConnectionsTableName: cardsmulti-connections-#{AWS::AccountId}-${self:custom.currentStage}
  gamesTableName: cardsmulti-games-#{AWS::AccountId}-${self:custom.currentStage}

provider:
  name: aws
  iamManagedPolicies:
  - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
  runtime: ${self:custom.lambdaRunTime}
  versionFunctions: false
  region: us-east-2
  timeout: 29

plugins:
  - serverless-pseudo-parameters

package:
  individually: true
  exclude:
    - "lib/**"
    - "node_modules/**"

layers:
  pythonPackageLayer:
    path: lib
    name: Python-Package-layer
    description: Python Package layer
    compatibleRuntimes:
      - ${self:custom.lambdaRunTime}

functions:
  connectHandler:
    handler: connect_handler.handle
    events:
      - websocket: $connect
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}

  disconnectHandler:
    handler: disconnect_handler.handle
    events:
      - websocket: $disconnect
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}

  onMessageHandler:
    handler: on_message_handler.handle
    events:
      - websocket:
          route: onMessage
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}

  onDataHandler:
    handler: on_data_handler.handle
    events:
      - websocket:
          route: onData
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }

  onRegisterHandler:
    handler: on_register_handler.handle
    events:
      - websocket:
          route: onRegister
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}
  
  onCreateGameHandler:
    handler: on_creategame_handler.handle
    events:
      - websocket:
          route: onCreateGame
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      GAMES_TABLE_NAME: ${self:custom.gamesTableName}
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}
  
  onJoinGameHandler:
    handler: on_joingame_handler.handle
    events:
      - websocket:
          route: onJoinGame
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      GAMES_TABLE_NAME: ${self:custom.gamesTableName}
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}

  onFindGameHandler:
    handler: on_findgame_handler.handle
    events:
      - websocket:
          route: onFindGame
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      GAMES_TABLE_NAME: ${self:custom.gamesTableName}

  onDisconnectGameHandler:
    handler: on_disconnectgame_handler.handle
    events:
      - websocket:
          route: onDisconnectGame
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      GAMES_TABLE_NAME: ${self:custom.gamesTableName}
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}

resources:
  Resources:
    socketConnectionsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.socketConnectionsTableName}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: gameIdIndex
            KeySchema:
              - AttributeName: gameId
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - connectionId
                - playerName
              ProjectionType: INCLUDE
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
    gamesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.gamesTableName}
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
          - AttributeName: gameCode
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
          - AttributeName: gameCode
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gameCodeIndex
            KeySchema:
              - AttributeName: gameCode
                KeyType: HASH
              - AttributeName: gameId
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - creator
                - players
              ProjectionType: INCLUDE
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true